include_guard(GLOBAL)

set(_greenfield_allow_system_dependencies OFF)
if(DEFINED CACHE{GREENFIELD_ALLOW_SYSTEM_DEPENDENCIES})
    set(_greenfield_allow_system_dependencies "${GREENFIELD_ALLOW_SYSTEM_DEPENDENCIES}")
endif()

if(DEFINED CACHE{GREENFIELD_BUILD_PROFILE} AND GREENFIELD_BUILD_PROFILE STREQUAL "headless-fast2d")
    message(STATUS "GREENFIELD_BUILD_PROFILE is headless-fast2d. Continuing without vcpkg.")
    return()
endif()

get_filename_component(_greenfield_source_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_greenfield_local_vcpkg_root "${_greenfield_source_dir}/.tools/vcpkg")

set(_greenfield_vcpkg_root "")
if(DEFINED ENV{VCPKG_ROOT} AND NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
    set(_greenfield_vcpkg_root "$ENV{VCPKG_ROOT}")
elseif(DEFINED CACHE{VCPKG_ROOT} AND NOT "${VCPKG_ROOT}" STREQUAL "")
    set(_greenfield_vcpkg_root "${VCPKG_ROOT}")
elseif(EXISTS "${_greenfield_local_vcpkg_root}/scripts/buildsystems/vcpkg.cmake")
    set(_greenfield_vcpkg_root "${_greenfield_local_vcpkg_root}")
endif()

if(_greenfield_vcpkg_root)
    set(_greenfield_vcpkg_toolchain "${_greenfield_vcpkg_root}/scripts/buildsystems/vcpkg.cmake")
    if(EXISTS "${_greenfield_vcpkg_toolchain}")
        include("${_greenfield_vcpkg_toolchain}")
    else()
        message(FATAL_ERROR "vcpkg was expected at ${_greenfield_vcpkg_root}, but scripts/buildsystems/vcpkg.cmake was not found. Run `make bootstrap` or set VCPKG_ROOT to a valid checkout.")
    endif()
elseif(_greenfield_allow_system_dependencies)
    message(STATUS "GREENFIELD_ALLOW_SYSTEM_DEPENDENCIES is ON. Continuing without vcpkg.")
else()
    message(FATAL_ERROR "vcpkg is required for the default developer flow. Run `make bootstrap` to clone and bootstrap a local checkout, or set VCPKG_ROOT to an existing vcpkg installation.")
endif()
